version: '3.8'

services:
  server:
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
  mf_drawer:
    build: ./src/mf_draw
