version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  mf_drawer:
    build: ./src/mf_drawer
    ports:
      - "3001:3001"
    volumes:
      - ./src/mf_drawer:/app
      - /app/node_modules
    command: npm run dev

  mf_videos:
    build: ./src/mf_videos
    ports:
      - "3002:3002"
    volumes:
      - ./src/mf_videos:/app
      - /app/node_modules
    command: npm run dev
